/// Pending-asset queue for proposals (MOD-FEAT-004 / DDD-11).
///
/// Holds asset additions / replacements that have not yet been
/// committed. The host (chat panel · MCP server · CLI extractor) pushes
/// proposals; the user / LLM client approves them via [approve], at
/// which point the queue replays through the patch pipeline so the
/// canonical sees a normal `apply()` event.
library;

import '../../core/asset_category_map.dart';
import '../../core/patch_pipeline.dart';
import '../../core/types.dart';

/// Where a proposal originated. Audit tag — keeps the user-facing log
/// honest about whether a change came from a chat turn, an MCP client,
/// or a batch extractor run.
enum ProposalSource {
  userIntent,
  autoBatch,
  mcpClient,
  importMerge,
}

/// One pending asset operation. The first cut is "add to a list at the
/// canonical pointer for [category]" — replace / supersede semantics
/// follow in a later round.
class AssetProposal {
  AssetProposal({
    required this.id,
    required this.category,
    required this.newAssetJson,
    required this.source,
    this.rationale,
    this.toolName,
  });

  /// Queue-local id (not the asset's own id). Generated by the queue
  /// when callers don't supply one.
  final String id;
  final AssetCategory category;
  final Map<String, dynamic> newAssetJson;
  final ProposalSource source;
  final String? rationale;

  /// MCP tool / chat tool name that produced the proposal. Surfaced in
  /// audit rows.
  final String? toolName;
}

/// FIFO queue of [AssetProposal]s. Stateless w.r.t. canonical state —
/// approval is the only path that mutates the bundle, and it goes
/// through the supplied [PatchPipeline] so dry-run validation, history
/// audit, and undo / redo all stay consistent.
class ReviewerQueue {
  ReviewerQueue({required PatchPipeline pipeline}) : _pipeline = pipeline;

  final PatchPipeline _pipeline;
  final List<AssetProposal> _pending = <AssetProposal>[];
  int _nextId = 1;

  List<AssetProposal> get pending => List.unmodifiable(_pending);

  /// Add [proposal] to the back of the queue. Returns the queue id —
  /// useful when the proposal didn't carry one and the caller needs it
  /// for later approval.
  String push(AssetProposal proposal) {
    _pending.add(proposal);
    return proposal.id;
  }

  /// Convenience builder — generates a queue id, wraps the asset JSON,
  /// and pushes. Returns the generated id.
  String pushNew({
    required AssetCategory category,
    required Map<String, dynamic> newAssetJson,
    required ProposalSource source,
    String? rationale,
    String? toolName,
  }) {
    final id = 'q-${_nextId++}';
    _pending.add(AssetProposal(
      id: id,
      category: category,
      newAssetJson: newAssetJson,
      source: source,
      rationale: rationale,
      toolName: toolName,
    ));
    return id;
  }

  /// Find a pending proposal by queue id.
  AssetProposal? find(String proposalId) {
    for (final p in _pending) {
      if (p.id == proposalId) return p;
    }
    return null;
  }

  /// Approve [proposalId] — translate to a JSON patch that appends the
  /// proposal's asset JSON to the matching canonical list, run the
  /// patch through [PatchPipeline.apply], and remove from the queue on
  /// success. Rejection (validation errors) leaves the proposal in
  /// place so the user can fix and retry.
  Future<PatchResult> approve(
    String proposalId, {
    required PatchOriginator originator,
  }) async {
    final proposal = find(proposalId);
    if (proposal == null) {
      throw StateError('proposal not found: $proposalId');
    }
    final snapshot = _pipeline.snapshotJson();
    final patch = _toPatch(proposal, snapshot);
    final result = await _pipeline.apply(patch, originator: originator);
    if (result is PatchApplied) {
      _pending.remove(proposal);
    }
    return result;
  }

  /// Drop [proposalId] without applying. [note] is purely advisory —
  /// the queue does not persist it; chat / audit hosts log separately.
  bool reject(String proposalId, {String? note}) {
    final p = find(proposalId);
    if (p == null) return false;
    _pending.remove(p);
    return true;
  }

  /// Drop everything. Used on project swap / dispose.
  void clear() => _pending.clear();

  /// Convert an [AssetProposal] to the JSON patch that adds the asset
  /// to its category-list. Inspects [snapshot] (the canonical bundle's
  /// current JSON) to decide whether to *initialize* the section
  /// container with a single-element list or *append* to the existing
  /// inner list. Without this branching, the section root would be
  /// re-emitted on every approve and RFC 6902 §4.1 add-on-existing-
  /// member semantics would silently overwrite the previously stored
  /// assets — see N-asset accumulation regression tests below.
  JsonPatchSet _toPatch(AssetProposal p, Map<String, dynamic> snapshot) {
    final desc = AssetCategoryMap.of(p.category);
    final ops = <PatchOp>[];
    final sectionPath = '/${desc.sectionKey}';
    final hasSection = snapshot[desc.sectionKey] != null;

    switch (p.category) {
      case AssetCategory.chunks:
        // KnowledgeSection.sources[0].documents — when /knowledge is
        // absent, provision the default source with the new document
        // already inside its `documents` list (single op, no const-
        // literal traps); otherwise append to the existing first
        // source's documents list. The two-op pattern (provision +
        // append) tripped over unmodifiable nested lists because the
        // first op carried `const PatchOp` whose inner empty literal
        // turned into an immutable list — the second `/.../documents/-`
        // append then threw `Cannot add to an unmodifiable list`. The
        // single-op pattern below mirrors what skill/profile/philosophy/
        // agent already do.
        if (!hasSection) {
          ops.add(PatchOp(
            op: 'add',
            path: '/knowledge',
            value: <String, dynamic>{
              'sources': <Map<String, dynamic>>[
                <String, dynamic>{
                  'id': 'default',
                  'name': 'default',
                  'type': 'unknown',
                  'documents': <Map<String, dynamic>>[p.newAssetJson],
                },
              ],
            },
          ));
        } else {
          ops.add(PatchOp(
            op: 'add',
            path: '/knowledge/sources/0/documents/-',
            value: p.newAssetJson,
          ));
        }
        return JsonPatchSet(ops);
      case AssetCategory.fact:
        // factGraphSection.embedded.facts — fact instance data lives in
        // the `factGraphSection` slot wired through McpBundle alongside
        // the `factGraphSchema` (type definitions) catalogue. Init
        // carries the first fact in `embedded.facts`; subsequent
        // approves append via `/-`.
        if (!hasSection) {
          ops.add(PatchOp(
            op: 'add',
            path: '/factGraphSection',
            value: <String, dynamic>{
              'mode': 'embedded',
              'embedded': <String, dynamic>{
                'facts': <Map<String, dynamic>>[p.newAssetJson],
              },
            },
          ));
        } else {
          ops.add(PatchOp(
            op: 'add',
            path: '$sectionPath/embedded/facts/-',
            value: p.newAssetJson,
          ));
        }
        return JsonPatchSet(ops);
      case AssetCategory.skill:
        if (!hasSection) {
          ops.add(PatchOp(
            op: 'add',
            path: sectionPath,
            value: <String, dynamic>{
              'modules': <Map<String, dynamic>>[p.newAssetJson],
            },
          ));
        } else {
          ops.add(PatchOp(
            op: 'add',
            path: '$sectionPath/modules/-',
            value: p.newAssetJson,
          ));
        }
        return JsonPatchSet(ops);
      case AssetCategory.profile:
        if (!hasSection) {
          ops.add(PatchOp(
            op: 'add',
            path: sectionPath,
            value: <String, dynamic>{
              'profiles': <Map<String, dynamic>>[p.newAssetJson],
            },
          ));
        } else {
          ops.add(PatchOp(
            op: 'add',
            path: '$sectionPath/profiles/-',
            value: p.newAssetJson,
          ));
        }
        return JsonPatchSet(ops);
      case AssetCategory.philosophy:
        if (!hasSection) {
          ops.add(PatchOp(
            op: 'add',
            path: sectionPath,
            value: <String, dynamic>{
              'philosophies': <Map<String, dynamic>>[p.newAssetJson],
            },
          ));
        } else {
          ops.add(PatchOp(
            op: 'add',
            path: '$sectionPath/philosophies/-',
            value: p.newAssetJson,
          ));
        }
        return JsonPatchSet(ops);
      case AssetCategory.agent:
        if (!hasSection) {
          ops.add(PatchOp(
            op: 'add',
            path: sectionPath,
            value: <String, dynamic>{
              'agents': <Map<String, dynamic>>[p.newAssetJson],
            },
          ));
        } else {
          ops.add(PatchOp(
            op: 'add',
            path: '$sectionPath/agents/-',
            value: p.newAssetJson,
          ));
        }
        return JsonPatchSet(ops);
    }
    // Suppress unreachable warning — silence by default.
    // ignore: dead_code
    return JsonPatchSet(ops);
  }
}
